### PR TITLE
Facilitate comparison of most recent guess and expected answer

### PR DESCRIPTION
**Pull request by ocram**
See https://github.com/sharkdp/quizzity/issues/1

### CODE REVIEW

**Comment by sharkdp** [comment]
I have not forgotten this, but didn't have time to look into this, so far. I'll report back soon. Thank you very much!

**Comment by sharkdp** [comment]
Very sorry for the huge delay.

This looks pretty cool! One problem is that the next city is already announced on the top. This also means that the timer will already run.

If we want to integrate this, we have to make sure to:
- Disable clicking while showing the zoomed-in map.
- Announce the new city only after we've zoomed out again.

**Comment by ocram** [comment]
Thanks, no problem!

As far as I can see, the second point should only be a matter of moving the next three statements into the new delayed closure as well, right?

The first point may perhaps be done by setting `pointer-events` to `none` and later changing back to `auto`, or by removing the click handler temporarily.

**Comment by sharkdp** [comment]
> As far as I can see, the second point should only be a matter of moving the next three statements into the new delayed closure as well, right?

It looks like it, yes.

> The first point may perhaps be done by setting `pointer-events` to `none` and later changing back to `auto`, or by removing the click handler temporarily.

:+1:

**Comment by sharkdp** [comment]
closing for now (cleaning up list of open PRs).

**Pull request closed without merging**
